flaskapp:
  build: ./
  env_file: .env
  dns:
    - 8.8.8.8
    - 9.9.9.9
  working_dir: /var/www/app
  command: bash -c "supervisord -c /etc/supervisord.conf"
  volumes:
    - ./app:/var/www/app:rw
    - ./supervisor/supervisord.conf:/etc/supervisord.conf:ro
    - ./supervisor/conf.d:/etc/supervisor/conf.d:ro
  links:
    - postgresql
    - redis
    - postfix
  environment:
    - APP_ENVIRONMENT=DEVELOPMENT
    - FLASK_SETTINGS=settings/dev.py
  ports:
    - "5000:5000"

postgresql:
  restart: always
  image: postgres:latest
  env_file: postgresql/.env
  volumes:
    - ./dockerfiles/pgdata:/var/lib/postgresql/data/pgdata:rw
  ports:
    - "5432:5432"

redis:
  restart: always
  image: redis:latest
  env_file: redis/.env
  volumes:
    - redis/redis.conf:/usr/local/etc/redis/redis.conf
  ports:
    - "6379:6379"

postfix:
  restart: always
  image: catatnight/postfix:latest
  env_file: postfix/.env
  ports:
    - "25:25"
