flaskapp:
  build: ./
  env_file: .env
  working_dir: /var/www/app
  command: bash -c "supervisord -n"
  volumes:
    - ./app:/var/www/app:rw
    - ./app/log:/var/www/app/log:rw
    - ./supervisor/supervisord.conf:/etc/supervisord.conf:ro
    - ./supervisor/conf.d:/etc/supervisor/conf.d:ro
  links:
    - postgresql
  environment:
    - PRODUCTION='true'
    - FLASK_SETTINGS=settings/prod.py

postgresql:
  restart: always
  image: postgres:latest
  env_file: .env
  volumes:
    - ./dockerfiles/pgdata:/var/lib/postgresql/data/pgdata:rw
  ports:
    - "5432:5432"

nginx:
  restart: always
  image: nginx:latest
  volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./nginx/flask_app.conf:/etc/nginx/sites-enabled/flask_app.conf:ro
    - ./app/run/uwsgi:/var/run/uwsgi:ro
  ports:
    - "80:80"
